server:
  port: 8080

#spring:
#  # datasource 数据源配置内容
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 1234
#  # JPA 配置内容，对应 JpaProperties 类
#  jpa:
#    show-sql: true # 打印 SQL 。生产环境，建议关闭
#    # Hibernate 配置内容，对应 HibernateProperties 类
#    hibernate:
#      ddl-auto: none

spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://10.20.0.57:3306/blockchain?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  # JPA 配置内容，对应 JpaProperties 类
  jpa:
    show-sql: true # 打印 SQL 。生产环境，建议关闭
    # Hibernate 配置内容，对应 HibernateProperties 类
    hibernate:
      ddl-auto: update

#server:
#  port: 4567
#
#spring:
#  datasource:
#    username: postgres
#    password: 123123
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect  #设置方言
#    properties:
#      hibernate:
#        jdbc.lob.non_contextual_creation: true #防止postgresql数据库因未实现CLOB格式而造成的数据检查出错
